# Build Multitarget Application & Deploy it to Cloud Foundry
name: Build MTA & Deploy it to CF (Trial)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ trial ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install MTA Build Tool
      run: npm install -g mbt
    # Do not generate package-lock.json
    # See https://blogs.sap.com/2020/07/07/escaping-eintegrity-hell/
    - name: Disable package-lock.json
      run: npm config set package-lock false
    - name: Build MTA
      run: mbt build -p cf
    - name: Deploy to Cloud Foundry
      uses: EnricoFerro/cf-cli-action@v2
      with:
        cf_api: ${{ secrets.CF_TRIAL_API }}
        cf_username: ${{ secrets.CF_USERNAME }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: ${{ secrets.CF_TRIAL_ORG }}
        cf_space: ${{ secrets.CF_TRIAL_SPACE }}
        command: deploy ./mta_archives/mockebanapp_1.0.0.mtar --retries 1

